#!/usr/bin/env bun
import { runAnalysis } from "@effect-native/repo-gaps"
import { Effect } from "effect"
import * as path from "node:path"

const PACKAGE_DIR = path.resolve(import.meta.dir, "../..")

Effect.runPromise(runAnalysis({
  packageDir: PACKAGE_DIR,
  packageName: "repo-gaps"
}))
