ignorePatchFailures: false

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

patchedDependencies:
  '@effect/sql-sqlite-react-native': patches/@effect__sql-sqlite-react-native.patch
  metro: patches/metro.patch
  react-native-reanimated: patches/react-native-reanimated.patch
