name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [effect-native/main, v4]
  push:
    branches: [effect-native/main, v4]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  types:
    name: Types
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: bun run check
      - run: bun run test-types --target '>=5.4'

  lint:
    name: Lint
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: bun run circular
      - run: bun run lint
      - run: bun run codegen
      - name: Check for codegen changes
        run: git diff --exit-code

  test:
    name: Test
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Test
        run: bun run test

  verify-subpaths:
    name: Verify Subpaths
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Verify effect subpath builds
        run: bun run verify-subpaths
