name: Release
on:
  push:
    branches: [effect-native/main, v4]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  release:
    if: github.repository_owner == 'effect-native'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Setup Node for npm Registry
        uses: actions/setup-node@v4
        with:
          node-version: "23.7.0"
          registry-url: "https://registry.npmjs.org"
          scope: "@effect-native"

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba
        with:
          version: bun run changeset-version
          publish: ${{ github.ref_name == 'v4' && 'bun run changeset-publish-beta' || 'bun run changeset-publish' }}
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
