name: Snapshot
on:
  pull_request:
    branches: [effect-native/main]
  workflow_dispatch:

permissions: {}

jobs:
  snapshot:
    name: Snapshot
    if: github.repository_owner == 'effect-native'
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Run codemods
        run: bun run codemod
      - name: Build package
        run: bun run build
      - name: Create snapshot
        id: snapshot
        run: bunx pkg-pr-new@0.0.28 publish --comment=off ./packages/*
